//
//  Images.swift
//  Neupass
//
//  Created by Manudeep N.s on 11/2/15.
//  Copyright © 2015 Manudeep Suresh. All rights reserved.
//

import Foundation
import UIKit

import UIKit

public extension UIDevice {
    
    var modelName: String {
        var systemInfo = utsname()
        uname(&systemInfo)
        let machineMirror = Mirror(reflecting: systemInfo.machine)
        let identifier = machineMirror.children.reduce("") { identifier, element in
            guard let value = element.value as? Int8 where value != 0 else { return identifier }
            return identifier + String(UnicodeScalar(UInt8(value)))
        }
        
        switch identifier {
        case "iPod5,1":                                 return "iPod Touch 5"
        case "iPod7,1":                                 return "iPod Touch 6"
        case "iPhone3,1", "iPhone3,2", "iPhone3,3":     return "iPhone 4"
        case "iPhone4,1":                               return "iPhone 4s"
        case "iPhone5,1", "iPhone5,2":                  return "iPhone 5"
        case "iPhone5,3", "iPhone5,4":                  return "iPhone 5c"
        case "iPhone6,1", "iPhone6,2":                  return "iPhone 5s"
        case "iPhone7,2":                               return "iPhone 6"
        case "iPhone7,1":                               return "iPhone 6 Plus"
        case "iPhone8,1":                               return "iPhone 6s"
        case "iPhone8,2":                               return "iPhone 6s Plus"
        case "iPad2,1", "iPad2,2", "iPad2,3", "iPad2,4":return "iPad 2"
        case "iPad3,1", "iPad3,2", "iPad3,3":           return "iPad 3"
        case "iPad3,4", "iPad3,5", "iPad3,6":           return "iPad 4"
        case "iPad4,1", "iPad4,2", "iPad4,3":           return "iPad Air"
        case "iPad5,3", "iPad5,4":                      return "iPad Air 2"
        case "iPad2,5", "iPad2,6", "iPad2,7":           return "iPad Mini"
        case "iPad4,4", "iPad4,5", "iPad4,6":           return "iPad Mini 2"
        case "iPad4,7", "iPad4,8", "iPad4,9":           return "iPad Mini 3"
        case "iPad5,1", "iPad5,2":                      return "iPad Mini 4"
        case "iPad6,7", "iPad6,8":                      return "iPad Pro"
        case "AppleTV5,3":                              return "Apple TV"
        case "i386", "x86_64":                          return "Simulator"
        default:                                        return identifier
        }
    }
    
}

let modelName = UIDevice.currentDevice().modelName
var IMAGE_SIZE_WIDTH: Int!
var IMAGE_SIZE_HEIGHT: Int!

var camoImage: [UIImage] = [
    UIImage(named: "camouflage1.jpg")!,
    UIImage(named: "camouflage2.jpg")!,
    UIImage(named: "camouflage3.jpg")!,
    UIImage(named: "camouflage4.jpg")!,
    UIImage(named: "camouflage5.jpg")!,
    UIImage(named: "camouflage6.jpg")!,
    UIImage(named: "camouflage7.jpg")!,
    UIImage(named: "camouflage8.jpg")!,
    UIImage(named: "camouflage9.jpg")!,
    UIImage(named: "camouflage10.jpg")!,
    UIImage(named: "camouflage11.jpg")!,
    UIImage(named: "camouflage12.jpg")!,
    UIImage(named: "camouflage13.jpg")!,
    UIImage(named: "camouflage14.jpg")!,
    UIImage(named: "camouflage15.jpg")!,
    UIImage(named: "camouflage16.jpg")!,
    UIImage(named: "camouflage17.jpg")!,
    UIImage(named: "camouflage18.jpg")!,
    UIImage(named: "camouflage19.jpg")!,
    UIImage(named: "camouflage20.jpg")!,
    UIImage(named: "camouflage21.jpg")!,
    UIImage(named: "camouflage22.jpg")!,
    UIImage(named: "camouflage23.jpg")!,
    UIImage(named: "camouflage24.jpg")!,
    UIImage(named: "camouflage25.jpg")!,
    UIImage(named: "camouflage26.jpg")!,
    UIImage(named: "camouflage27.jpg")!,
    UIImage(named: "camouflage28.jpg")!,
    UIImage(named: "camouflage29.jpg")!,
    UIImage(named: "camouflage30.jpg")!,
    UIImage(named: "camouflage31.jpg")!,
    UIImage(named: "camouflage32.jpg")!,
    UIImage(named: "camouflage33.jpg")!,
    UIImage(named: "camouflage34.jpg")!,
    UIImage(named: "camouflage35.jpg")!,
    UIImage(named: "camouflage36.jpg")!,
    UIImage(named: "camouflage37.jpg")!,
    UIImage(named: "camouflage38.jpg")!,
    UIImage(named: "camouflage39.jpg")!,
    UIImage(named: "camouflage40.jpg")!,
    UIImage(named: "camouflage41.jpg")!,
    UIImage(named: "camouflage42.jpg")!,
    UIImage(named: "camouflage43.jpg")!,
    UIImage(named: "camouflage44.jpg")!,
    UIImage(named: "camouflage45.jpg")!,
    UIImage(named: "camouflage46.jpg")!,
    UIImage(named: "camouflage47.jpg")!,
    UIImage(named: "camouflage48.jpg")!,
    UIImage(named: "camouflage49.jpg")!,
    UIImage(named: "camouflage50.jpg")!,
    UIImage(named: "camouflage51.jpg")!,
    UIImage(named: "camouflage52.jpg")!,
    UIImage(named: "camouflage53.jpg")!,
    UIImage(named: "camouflage54.jpg")!,
    UIImage(named: "camouflage55.jpg")!,
    UIImage(named: "camouflage56.jpg")!,
    UIImage(named: "camouflage57.jpg")!,
    UIImage(named: "camouflage58.jpg")!,
    UIImage(named: "camouflage59.jpg")!,
    UIImage(named: "camouflage60.jpg")!,
    UIImage(named: "camouflage61.jpg")!,
    UIImage(named: "camouflage62.jpg")!,
    UIImage(named: "camouflage63.jpg")!,
    UIImage(named: "camouflage64.jpg")!,
    UIImage(named: "camouflage65.jpg")!,
    UIImage(named: "camouflage66.jpg")!,
    UIImage(named: "camouflage67.jpg")!,
    UIImage(named: "camouflage68.jpg")!,
    UIImage(named: "camouflage69.jpg")!,
    UIImage(named: "camouflage70.jpg")!,
    UIImage(named: "camouflage71.jpg")!,
    UIImage(named: "camouflage72.jpg")!,
    UIImage(named: "camouflage73.jpg")!,
    UIImage(named: "camouflage74.jpg")!,
    UIImage(named: "camouflage75.jpg")!,
    UIImage(named: "camouflage76.jpg")!,
    UIImage(named: "camouflage77.jpg")!,
    UIImage(named: "camouflage78.jpg")!,
    UIImage(named: "camouflage79.jpg")!,
    UIImage(named: "camouflage80.jpg")!,
    UIImage(named: "camouflage81.jpg")!,
    UIImage(named: "camouflage82.jpg")!,
    UIImage(named: "camouflage83.jpg")!,
    UIImage(named: "camouflage84.jpg")!,
    UIImage(named: "camouflage85.jpg")!,
    UIImage(named: "camouflage86.jpg")!,
    UIImage(named: "camouflage87.jpg")!,
    UIImage(named: "camouflage88.jpg")!,
    UIImage(named: "camouflage89.jpg")!,
    UIImage(named: "camouflage90.jpg")!,
    UIImage(named: "camouflage91.jpg")!,
    UIImage(named: "camouflage92.jpg")!,
    UIImage(named: "camouflage93.jpg")!,
    UIImage(named: "camouflage94.jpg")!,
    UIImage(named: "camouflage95.jpg")!,
    UIImage(named: "camouflage96.jpg")!,
    UIImage(named: "camouflage97.jpg")!,
    UIImage(named: "camouflage98.jpg")!,
    UIImage(named: "camouflage99.jpg")!,
    UIImage(named: "camouflage100.jpg")!,
    UIImage(named: "camouflage101.jpg")!,
    UIImage(named: "camouflage102.jpg")!,
    UIImage(named: "camouflage103.jpg")!,
    UIImage(named: "camouflage104.jpg")!,
    UIImage(named: "camouflage105.jpg")!,
    UIImage(named: "camouflage106.jpg")!,
    UIImage(named: "camouflage107.jpg")!,
    UIImage(named: "camouflage108.jpg")!,
    UIImage(named: "camouflage109.jpg")!,
    UIImage(named: "camouflage110.jpg")!,
    UIImage(named: "camouflage111.jpg")!,
    UIImage(named: "camouflage112.jpg")!,
    UIImage(named: "camouflage113.jpg")!,
    UIImage(named: "camouflage114.jpg")!,
    UIImage(named: "camouflage115.jpg")!,
    UIImage(named: "camouflage116.jpg")!,
    UIImage(named: "camouflage117.jpg")!,
    UIImage(named: "camouflage118.jpg")!,
    UIImage(named: "camouflage119.jpg")!,
    UIImage(named: "camouflage120.jpg")!,
    UIImage(named: "camouflage121.jpg")!,
    UIImage(named: "camouflage122.jpg")!,
    UIImage(named: "camouflage123.jpg")!,
    UIImage(named: "camouflage124.jpg")!,
    UIImage(named: "camouflage125.jpg")!,
    UIImage(named: "camouflage126.jpg")!,
    UIImage(named: "camouflage127.jpg")!,
    UIImage(named: "camouflage128.jpg")!,
    UIImage(named: "camouflage129.jpg")!,
    UIImage(named: "camouflage130.jpg")!,
    UIImage(named: "camouflage131.jpg")!,
    UIImage(named: "camouflage132.jpg")!,
    UIImage(named: "camouflage133.jpg")!,
    UIImage(named: "camouflage134.jpg")!,
    UIImage(named: "camouflage135.jpg")!,
    UIImage(named: "camouflage136.jpg")!,
    UIImage(named: "camouflage137.jpg")!,
    UIImage(named: "camouflage138.jpg")!,
    UIImage(named: "camouflage139.jpg")!,
    UIImage(named: "camouflage140.jpg")!,
    UIImage(named: "camouflage141.jpg")!,
    UIImage(named: "camouflage142.jpg")!,
    UIImage(named: "camouflage143.jpg")!,
    UIImage(named: "camouflage144.jpg")!,
    UIImage(named: "camouflage145.jpg")!,
    UIImage(named: "camouflage146.jpg")!,
    UIImage(named: "camouflage147.jpg")!,
    UIImage(named: "camouflage148.jpg")!,
    UIImage(named: "camouflage149.jpg")!,
    UIImage(named: "camouflage150.jpg")!,
    UIImage(named: "camouflage151.jpg")!,
    UIImage(named: "camouflage152.jpg")!,
    UIImage(named: "camouflage153.jpg")!,
    UIImage(named: "camouflage154.jpg")!,
    UIImage(named: "camouflage156.jpg")!,
    UIImage(named: "camouflage157.jpg")!,
    UIImage(named: "camouflage158.jpg")!,
    UIImage(named: "camouflage159.jpg")!,
    UIImage(named: "camouflage160.jpg")!,
    UIImage(named: "camouflage161.jpg")!,
    UIImage(named: "camouflage162.jpg")!,
    UIImage(named: "camouflage163.jpg")!,
    UIImage(named: "camouflage164.jpg")!,
    UIImage(named: "camouflage165.jpg")!,
    UIImage(named: "camouflage166.jpg")!,
    UIImage(named: "camouflage167.jpg")!,
    UIImage(named: "camouflage168.jpg")!,
    UIImage(named: "camouflage169.jpg")!,
    UIImage(named: "camouflage170.jpg")!,
    UIImage(named: "camouflage171.jpg")!,
    UIImage(named: "camouflage172.jpg")!,
    UIImage(named: "camouflage173.jpg")!,
    UIImage(named: "camouflage174.jpg")!,
    UIImage(named: "camouflage175.jpg")!,
    UIImage(named: "camouflage176.jpg")!,
    UIImage(named: "camouflage177.jpg")!,
    UIImage(named: "camouflage178.jpg")!,
    UIImage(named: "camouflage179.jpg")!,
    UIImage(named: "camouflage180.jpg")!,
    UIImage(named: "camouflage181.jpg")!,
    UIImage(named: "camouflage182.jpg")!,
    UIImage(named: "camouflage183.jpg")!,
    UIImage(named: "camouflage184.jpg")!,
    UIImage(named: "camouflage185.jpg")!,
    UIImage(named: "camouflage186.jpg")!,
    UIImage(named: "camouflage187.jpg")!,
    UIImage(named: "camouflage188.jpg")!,
    UIImage(named: "camouflage189.jpg")!,
    UIImage(named: "camouflage190.jpg")!,
    UIImage(named: "camouflage191.jpg")!,
    UIImage(named: "camouflage192.jpg")!,
    UIImage(named: "camouflage193.jpg")!,
    UIImage(named: "camouflage194.jpg")!,
    UIImage(named: "camouflage195.jpg")!,
    UIImage(named: "camouflage196.jpg")!,
    UIImage(named: "camouflage197.jpg")!,
    UIImage(named: "camouflage198.jpg")!,
    UIImage(named: "camouflage199.jpg")!,
    UIImage(named: "camouflage200.jpg")!,
    UIImage(named: "camouflage201.jpg")!,
    UIImage(named: "camouflage202.jpg")!,
    UIImage(named: "camouflage203.jpg")!,
    UIImage(named: "camouflage204.jpg")!,
    UIImage(named: "camouflage205.jpg")!,
    UIImage(named: "camouflage206.jpg")!,
    UIImage(named: "camouflage207.jpg")!,
    UIImage(named: "camouflage208.jpg")!,
    UIImage(named: "camouflage209.jpg")!,
    UIImage(named: "camouflage210.jpg")!,
    UIImage(named: "camouflage211.jpg")!,
    UIImage(named: "camouflage212.jpg")!,
    UIImage(named: "camouflage213.jpg")!,
    UIImage(named: "camouflage214.jpg")!,
    UIImage(named: "camouflage215.jpg")!,
    UIImage(named: "camouflage216.jpg")!,
    UIImage(named: "camouflage217.jpg")!,
    UIImage(named: "camouflage218.jpg")!,
    UIImage(named: "camouflage219.jpg")!,
    UIImage(named: "camouflage220.jpg")!,
    UIImage(named: "camouflage221.jpg")!,
    UIImage(named: "camouflage222.jpg")!,
    UIImage(named: "camouflage223.jpg")!,
    UIImage(named: "camouflage224.jpg")!,
    UIImage(named: "camouflage225.jpg")!,
    UIImage(named: "camouflage226.jpg")!,
    UIImage(named: "camouflage227.jpg")!,
    UIImage(named: "camouflage228.jpg")!,
    UIImage(named: "camouflage229.jpg")!,
    UIImage(named: "camouflage230.jpg")!,
    UIImage(named: "camouflage231.jpg")!,
    UIImage(named: "camouflage232.jpg")!,
    UIImage(named: "camouflage233.jpg")!,
    UIImage(named: "camouflage234.jpg")!,
    UIImage(named: "camouflage235.jpg")!,
    UIImage(named: "camouflage236.jpg")!,
    UIImage(named: "camouflage237.jpg")!,
    UIImage(named: "camouflage238.jpg")!,
    UIImage(named: "camouflage239.jpg")!,
    UIImage(named: "camouflage240.jpg")!,
    UIImage(named: "camouflage241.jpg")!,
    UIImage(named: "camouflage242.jpg")!,
    UIImage(named: "camouflage243.jpg")!,
    UIImage(named: "camouflage244.jpg")!,
    UIImage(named: "camouflage245.jpg")!,
    UIImage(named: "camouflage246.jpg")!,
    UIImage(named: "camouflage247.jpg")!,
    UIImage(named: "camouflage248.jpg")!,
    UIImage(named: "camouflage249.jpg")!,
    UIImage(named: "camouflage250.jpg")!,
    UIImage(named: "camouflage251.jpg")!,
    UIImage(named: "camouflage252.jpg")!,
    UIImage(named: "camouflage253.jpg")!,
    UIImage(named: "camouflage254.jpg")!,
    UIImage(named: "camouflage255.jpg")!,
    UIImage(named: "camouflage256.jpg")!,
    UIImage(named: "camouflage257.jpg")!,
    UIImage(named: "camouflage258.jpg")!,
    UIImage(named: "camouflage259.jpg")!,
    UIImage(named: "camouflage260.jpg")!,
    UIImage(named: "camouflage261.jpg")!,
    UIImage(named: "camouflage262.jpg")!,
    UIImage(named: "camouflage263.jpg")!,
    UIImage(named: "camouflage264.jpg")!,
    UIImage(named: "camouflage265.jpg")!,
    UIImage(named: "camouflage266.jpg")!,
    UIImage(named: "camouflage267.jpg")!,
    UIImage(named: "camouflage268.jpg")!,
    UIImage(named: "camouflage269.jpg")!,
    UIImage(named: "camouflage270.jpg")!,
    UIImage(named: "camouflage271.jpg")!,
    UIImage(named: "camouflage272.jpg")!,
    UIImage(named: "camouflage273.jpg")!,
    UIImage(named: "camouflage274.jpg")!,
    UIImage(named: "camouflage275.jpg")!,
    UIImage(named: "camouflage276.jpg")!,
    UIImage(named: "camouflage278.jpg")!,
    UIImage(named: "camouflage279.jpg")!,
    UIImage(named: "camouflage280.jpg")!,
    UIImage(named: "camouflage281.jpg")!,
    UIImage(named: "camouflage282.jpg")!,
    UIImage(named: "camouflage283.jpg")!,
    UIImage(named: "camouflage284.jpg")!,
    UIImage(named: "camouflage285.jpg")!,
    UIImage(named: "camouflage286.jpg")!,
    UIImage(named: "camouflage287.jpg")!,
    UIImage(named: "camouflage288.jpg")!,
    UIImage(named: "camouflage289.jpg")!,
    UIImage(named: "camouflage290.jpg")!,
    UIImage(named: "camouflage291.jpg")!,
    UIImage(named: "camouflage292.jpg")!,
    UIImage(named: "camouflage293.jpg")!,
    UIImage(named: "camouflage294.jpg")!,
    UIImage(named: "camouflage295.jpg")!,
    UIImage(named: "camouflage296.jpg")!,
    UIImage(named: "camouflage297.jpg")!,
    UIImage(named: "camouflage298.jpg")!,
    UIImage(named: "camouflage299.jpg")!,
    UIImage(named: "camouflage300.jpg")!
]